before_install:
  - sudo apt-get update -qq
  - sudo apt-get install texlive texlive-fonts-recommended texlive-lang-spanish texlive-latex-base texlive-latex-extra texlive-latex-recommended
script: make clean curric.pdf
after_success: bash update-pdf-file.sh
